### ISSUE TITLE
Update Crud example from new Api node 

### ISSUE THREAD

**Issue by PierreBrisorgueil** [weareopensource/MEANie#54]
new CRUD available on NODE Dev branch :)

you can test on mongo or sequelize just by change the controller called in route file of the task module  :)

**Comment by techla** [comment]
Soooo ... the D day is close. For this PR, I get ride of the session handler since we switched to a frontend app equiped with JWT. The code is still there but the luncher function is commented out.
Some mongoose object population have been canceled since we need normalized datas to be stored into the store. That's it. Enjoy

**Comment by techla** [comment]
modulo weareopensource/Node#24 and weareopensource/Angular#67 PRs. they both related to this issue. I should mention that.
